# Generated by Django 2.1.7 on 2019-03-23 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('speed_per_hour', models.IntegerField(default=0, verbose_name='Скорость')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ('equipment_class',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Класс оборудования')),
            ],
            options={
                'verbose_name': 'Класс оборудования',
                'verbose_name_plural': 'Классы оборудования',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('deadline',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('equipment_classes', models.ManyToManyField(to='biocad.EquipmentClass')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biocad.Product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biocad.EquipmentClass', verbose_name='Класс оборудования'),
        ),
    ]
