# Generated by Django 2.1.7 on 2019-03-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biocad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentclass',
            options={'ordering': ('name',), 'verbose_name': 'Класс оборуования', 'verbose_name_plural': 'Классы оборудования'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='end_maintenance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец тех. работ'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='start_maintenance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало тех. работ'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biocad.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_work_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
